FROM centos:7
MAINTAINER bhrth.dsra1@gmail.com
RUN yum install -y \
    tree \
    emacs \
    httpd \
    traceroute 
EXPOSE 80 100 200 300 400 500
ENV var1=ping var2=8.8.8.8
#CMD $var1 $var2
VOLUME /data
ENTRYPOINT ["httpd"]
CMD ["-D","FOREGROUND"]
